In [1]:
import pandas as pd
import numpy as np

data = {
    "customer_id":  [1, 2, 3, 4, 5, 6, 7, 8],
    "age":          [23, 45, "N/A", 31, np.nan, 52, 28, 33],
    "gender":       ["M", "Female", "male", "N/A", "F", "", "Male", "female"],
    "purchase_amt": [120.5, np.nan, 340.0, 89.0, 456.0, "null", 210.0, np.nan],
    "city":         ["Mumbai", "Delhi", "Mumbai", "?", "Chennai", "Delhi", "N/A", "Pune"],
    "subscribed":   ["Yes", "No", "Yes", "Yes", np.nan, "No", "Yes", "No"]
}

df = pd.DataFrame(data)

In [2]:
df

   customer_id  age  gender purchase_amt     city subscribed
0            1   23       M        120.5   Mumbai        Yes
1            2   45  Female          NaN    Delhi         No
2            3  N/A    male        340.0   Mumbai        Yes
3            4   31     N/A         89.0        ?        Yes
4            5  NaN       F        456.0  Chennai        NaN
5            6   52                 null    Delhi         No
6            7   28    Male        210.0      N/A        Yes
7            8   33  female          NaN     Pune         No

##  Lets Check the Missing values detected by Pandas :

In [3]:
df.isna().sum()

customer_id     0
age             1
gender          0
purchase_amt    2
city            0
subscribed      1
dtype: int64

In [4]:
df_clean = df.replace(["N/A",''," ", "null","?",], np.nan)
df_clean

/tmp/ipykernel_418/3867525823.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_clean = df.replace(["N/A",''," ", "null","?",], np.nan)

   customer_id   age  gender  purchase_amt     city subscribed
0            1  23.0       M         120.5   Mumbai        Yes
1            2  45.0  Female           NaN    Delhi         No
2            3   NaN    male         340.0   Mumbai        Yes
3            4  31.0     NaN          89.0      NaN        Yes
4            5   NaN       F         456.0  Chennai        NaN
5            6  52.0     NaN           NaN    Delhi         No
6            7  28.0    Male         210.0      NaN        Yes
7            8  33.0  female           NaN     Pune         No

In [5]:
df_clean.isna().sum()

customer_id     0
age             2
gender          2
purchase_amt    3
city            2
subscribed      1
dtype: int64

## - Missing data per Columns

In [6]:
missing_data_pct = (df_clean.isna().sum() / df_clean.shape[0]) * 100

print("Missing data per Cols in %: ")
print(missing_data_pct)

Missing data per Cols in %:
customer_id      0.0
age             25.0
gender          25.0
purchase_amt    37.5
city            25.0
subscribed      12.5
dtype: float64

## 1. 'Age' column in each column, we can easily replace the values with the median values as replacing the values with mean or average values will not be a good representative in a skewed you data.

In [7]:
df_clean["age"]

0    23.0
1    45.0
2     NaN
3    31.0
4     NaN
5    52.0
6    28.0
7    33.0
Name: age, dtype: float64

## 2. In the "gender" column, as this column is a categorical feature, we can replace the values with mode or most frequent value - because that's the correct way of doing it

In [8]:
df_clean["gender"]

0         M
1    Female
2      male
3       NaN
4         F
5       NaN
6      Male
7    female
Name: gender, dtype: object

## 3. Now the "purchased amount" column. This column is interesting because this would be the target variable. So for that reason I'll not be doing anything with this or simply will try to think to drop the rows with the null values.

In [9]:
df_clean["purchase_amt"]

0    120.5
1      NaN
2    340.0
3     89.0
4    456.0
5      NaN
6    210.0
7      NaN
Name: purchase_amt, dtype: float64

## 4. In the "city" column, as it is also a categorical attribute, I will replace the values with mode.

In [10]:
df_clean["city"]

0     Mumbai
1      Delhi
2     Mumbai
3        NaN
4    Chennai
5      Delhi
6        NaN
7       Pune
Name: city, dtype: object

## 5. And the last "subscribed" column, I will replace the value with - I think mode cuz - I can see It's a binary column, but it's an also categorical column. So according to me, we should replace it with mode.

In [11]:
df_clean["subscribed"]

0    Yes
1     No
2    Yes
3    Yes
4    NaN
5     No
6    Yes
7     No
Name: subscribed, dtype: object

In [12]:
df_clean

   customer_id   age  gender  purchase_amt     city subscribed
0            1  23.0       M         120.5   Mumbai        Yes
1            2  45.0  Female           NaN    Delhi         No
2            3   NaN    male         340.0   Mumbai        Yes
3            4  31.0     NaN          89.0      NaN        Yes
4            5   NaN       F         456.0  Chennai        NaN
5            6  52.0     NaN           NaN    Delhi         No
6            7  28.0    Male         210.0      NaN        Yes
7            8  33.0  female           NaN     Pune         No

## Starting with the first column: "Age"

In [13]:
print(df_clean["age"].isna().sum())
df_clean["age"] = df_clean["age"].fillna(df_clean["age"].median())
df_clean["age"]

2

0    23.0
1    45.0
2    32.0
3    31.0
4    32.0
5    52.0
6    28.0
7    33.0
Name: age, dtype: float64

## it's time for "Gender" column

In [24]:
df_clean["gender"].isna().sum()

np.int64(2)

In [25]:
df_clean["gender"]

0      Male
1    Female
2      Male
3       NaN
4         F
5       NaN
6      Male
7    female
Name: gender, dtype: object

In [26]:
df_clean["gender"].unique()

array(['Male', 'Female', nan, 'F', 'female'], dtype=object)

In [27]:
df_clean["gender"] = df_clean["gender"].replace(['M','male'],"Male") # replacing male values
df_clean["gender"]

0      Male
1    Female
2      Male
3       NaN
4         F
5       NaN
6      Male
7    female
Name: gender, dtype: object

In [32]:
df_clean["gender"] = df_clean["gender"] = df_clean["gender"].replace(['f',"female",'F'],"Female") # replacing female values
df_clean["gender"]

0      Male
1    Female
2      Male
3       NaN
4    Female
5       NaN
6      Male
7    Female
Name: gender, dtype: object

In [40]:
df_clean["gender"] = df_clean["gender"].fillna(df_clean["gender"].mode()[0])
df_clean["gender"]

0      Male
1    Female
2      Male
3    Female
4    Female
5    Female
6      Male
7    Female
Name: gender, dtype: object

## Now "purchase amount" column

In [41]:
df_clean

   customer_id   age  gender  purchase_amt     city subscribed
0            1  23.0    Male         120.5   Mumbai        Yes
1            2  45.0  Female           NaN    Delhi         No
2            3  32.0    Male         340.0   Mumbai        Yes
3            4  31.0  Female          89.0      NaN        Yes
4            5  32.0  Female         456.0  Chennai        NaN
5            6  52.0  Female           NaN    Delhi         No
6            7  28.0    Male         210.0      NaN        Yes
7            8  33.0  Female           NaN     Pune         No

In [53]:
df_clean_reduced = df_clean.dropna(subset=['purchase_amt'])
print("Purchase amt:\n", df_clean_reduced["purchase_amt"])
df_clean_reduced = df_clean_reduced.reset_index(drop = True)
df_clean_reduced

Purchase amt:
 0    120.5
2    340.0
3     89.0
4    456.0
6    210.0
Name: purchase_amt, dtype: float64

   customer_id   age  gender  purchase_amt     city subscribed
0            1  23.0    Male         120.5   Mumbai        Yes
1            3  32.0    Male         340.0   Mumbai        Yes
2            4  31.0  Female          89.0      NaN        Yes
3            5  32.0  Female         456.0  Chennai        NaN
4            7  28.0    Male         210.0      NaN        Yes

## cleaning the "city" attribute.

In [54]:
df_clean_reduced["city"]

0     Mumbai
1     Mumbai
2        NaN
3    Chennai
4        NaN
Name: city, dtype: object

In [55]:
df_clean_reduced["city"] = df_clean_reduced["city"].fillna(df_clean_reduced["city"].mode()[0])
df_clean_reduced

   customer_id   age  gender  purchase_amt     city subscribed
0            1  23.0    Male         120.5   Mumbai        Yes
1            3  32.0    Male         340.0   Mumbai        Yes
2            4  31.0  Female          89.0   Mumbai        Yes
3            5  32.0  Female         456.0  Chennai        NaN
4            7  28.0    Male         210.0   Mumbai        Yes

## now the "subscribed" column

In [56]:
df_clean_reduced["subscribed"]

0    Yes
1    Yes
2    Yes
3    NaN
4    Yes
Name: subscribed, dtype: object

In [57]:
df_clean_reduced["subscribed"].isna().sum()

np.int64(1)

In [58]:
df_clean_reduced["subscribed_was_missing"] = df_clean_reduced["subscribed"].isna().astype(int)
df_clean_reduced["subscribed_was_missing"]

0    0
1    0
2    0
3    1
4    0
Name: subscribed_was_missing, dtype: int64

In [60]:
df_clean_reduced["subscribed"] = df_clean_reduced["subscribed"].fillna(df_clean_reduced["subscribed"].mode()[0])
df_clean_reduced["subscribed"]

0    Yes
1    Yes
2    Yes
3    Yes
4    Yes
Name: subscribed, dtype: object

In [64]:
# Verify - ing
df_clean_reduced["subscribed"].isna().sum()

np.int64(0)

In [72]:
# Final verification
print("Final Missing values: ")
print()
print(df_clean_reduced.isna().sum())
print()

print("Shape: ",df_clean_reduced.shape)
print()
print("Dtypes: ",df_clean_reduced.dtypes)

Final Missing values:

customer_id               0
age                       0
gender                    0
purchase_amt              0
city                      0
subscribed                0
subscribed_was_missing    0
dtype: int64

Shape:  (5, 7)

Dtypes:  customer_id                 int64
age                       float64
gender                     object
purchase_amt              float64
city                       object
subscribed                 object
subscribed_was_missing      int64
dtype: object